### ISSUE TITLE
[urgent] BUG after follow update.

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1140]
```
Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hartexcraft2.nl2_topics_following' doesn't exist in /var/www/work/hc/core/classes/DB.php:51
Stack trace:
#0 /var/www/work/hc/core/classes/DB.php(51): PDOStatement->execute()
#1 /var/www/work/hc/modules/Forum/pages/forum/view_topic.php(596): DB->query('SELECT id, exis...', Array)
#2 /var/www/work/hc/index.php(103): require('/var/www/work/h...')
#3 {main}
  thrown
in file /var/www/work/hc/core/classes/DB.php
```

EDIT: this is a fresh install.

**Comment by samerton** [comment]
9c99d3eb5d9a009427c36f33361bc730549f3855
