### ISSUE TITLE
Donate addon fails to sync

### ISSUE THREAD

**Issue by Permanently** [NamelessMC/Nameless#1171]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? Latest (1.0.21)
* How would you describe the issue? Every time I try syncing my Buycraft web store
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? Here's a MySQL syntax error from my Apache error log.
```
[Wed Jul 18 11:30:53.896810 2018] [:error] [pid 19184] [client 162.158.154.31:34255] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order``) VALUES ('Commands', '1191382', '1')' at line 1 in /var/www/theundefined.uk/public_html/core/classes/DB.php:68\nStack trace:\n#0 /var/www/theundefined.uk/public_html/core/classes/DB.php(68): PDOStatement->execute()\n#1 /var/www/theundefined.uk/public_html/core/classes/DB.php(167): DB->createQuery('INSERT INTO nl1...', Array)\n#2 /var/www/theundefined.uk/public_html/core/classes/Queries.php(42): DB->insert('nl1_donation_ca...', Array)\n#3 /var/www/theundefined.uk/public_html/addons/Donate/sync.php(56): Queries->create('donation_catego...', Array)\n#4 {main}\n  thrown in /var/www/theundefined.uk/public_html/core/classes/DB.php on line 68, referer: https://theundefined.uk/admin/addons/?action=edit&addon=Donate&do=sync
[Wed Jul 18 11:31:02.741751 2018] [:error] [pid 20688] [client 141.101.99.209:29853] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order``) VALUES ('Commands', '1191382', '1')' at line 1 in /var/www/theundefined.uk/public_html/core/classes/DB.php:68\nStack trace:\n#0 /var/www/theundefined.uk/public_html/core/classes/DB.php(68): PDOStatement->execute()\n#1 /var/www/theundefined.uk/public_html/core/classes/DB.php(167): DB->createQuery('INSERT INTO nl1...', Array)\n#2 /var/www/theundefined.uk/public_html/core/classes/Queries.php(42): DB->insert('nl1_donation_ca...', Array)\n#3 /var/www/theundefined.uk/public_html/addons/Donate/sync.php(56): Queries->create('donation_catego...', Array)\n#4 {main}\n  thrown in /var/www/theundefined.uk/public_html/core/classes/DB.php on line 68

```
* Do you have an idea how or where the issue occurs? Whenever Synchronise is clicked, or whenever the Buycraft "secret sync" URL is accessed. Error 500.
* What Modules are you using? Addons > Donate
* What theme are you using? Cosmo

**Comment by samerton** [comment]
Can you edit the file **addons/Donate/sync.php** in a text editor, delete all code inside + replace with [this new code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/addons/Donate/sync.php)?

**Comment by Permanently** [comment]
Working completely fine now. Thanks!
