### ISSUE TITLE
Fatal error when enabling LatestPostsWidget

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#1957]
```
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND `view` = 1 AND view_other_topics = 1' at line 1 in /var/www/nmc.tadhgboyle.dev/core/classes/DB.php:51 Stack trace: #0 /var/www/nmc.tadhgboyle.dev/core/classes/DB.php(51): PDOStatement->execute() #1 /var/www/nmc.tadhgboyle.dev/modules/Forum/classes/Forum.php(161): DB->query() #2 /var/www/nmc.tadhgboyle.dev/modules/Forum/widgets/LatestPostsWidget.php(67): Forum->getLatestDiscussions() #3 /var/www/nmc.tadhgboyle.dev/core/classes/Widgets.php(101): LatestPostsWidget->initialise() #4 /var/www/nmc.tadhgboyle.dev/modules/Core/pages/home.php(54): Widgets->getWidgets() #5 /var/www/nmc.tadhgboyle.dev/modules/Core/pages/index.php(16): require('/var/www/nmc.ta...') #6 /var/www/nmc.tadhgboyle.dev/index.php(71): require('/var/www/nmc.ta...') #7 {main} thrown in /var/www/nmc.tadhgboyle.dev/core/classes/DB.php on line 51
```
![img](https://i.imgur.com/fw6fzpw.png)

**Comment by partydragen** [comment]
Fixed, Had forgot to update that file to the repo
