### ISSUE TITLE
PHP 8: Error when enabling discord integration

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1987]
```
Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /data/modules/Core/pages/panel/discord.php:47
Stack trace:
#0 /data/index.php(84): require()
#1 {main}
```

After pressing 'back', discord integration did enable properly.

**Comment by Aberdeener** [comment]
Likely same as other error,
try with this commit 3a3360c and let me know either way

**Comment by Derkades** [comment]
No, not fixed yet. Different line numbers now:
```
Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /data/modules/Core/pages/panel/discord.php:47
Stack trace:
#0 /data/index.php(86): require()
#1 {main}
```

**Comment by Derkades** [comment]
It is fixed now
