### ISSUE TITLE
PHP 8: Error loading group sync page

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#1989]
```
Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /data/cache/templates_c/8902a8da8f9527018cd8a9dd0cf8193f2c069f2d_0.file.api_group_sync.tpl.php:210
Stack trace:
#0 /data/core/includes/smarty/sysplugins/smarty_template_resource_base.php(123): content_5fe79be4905995_65553454(Object(Smarty_Internal_Template))
#1 /data/core/includes/smarty/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /data/core/includes/smarty/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /data/core/includes/smarty/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#4 /data/core/includes/smarty/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#5 /data/core/classes/TemplateBase.php(101): Smarty_Internal_TemplateBase->display('core/api_group_...')
#6 /data/modules/Core/pages/panel/api.php(468): TemplateBase->displayTemplate('core/api_group_...', Object(Smarty))
#7 /data/index.php(84): require('/data/modules/C...')
#8 {main}
  ```

**Comment by Aberdeener** [comment]
Can you try again from this commit 3a3360c and let me know if it fixes it?

**Comment by Derkades** [comment]
Not fixed yet for me, I did a complete reinstall.
```
Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /data/cache/templates_c/8902a8da8f9527018cd8a9dd0cf8193f2c069f2d_0.file.api_group_sync.tpl.php:210
Stack trace:
#0 /data/core/includes/smarty/sysplugins/smarty_template_resource_base.php(123): content_5fe870ac314a55_58313702(Object(Smarty_Internal_Template))
#1 /data/core/includes/smarty/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /data/core/includes/smarty/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /data/core/includes/smarty/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#4 /data/core/includes/smarty/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#5 /data/core/classes/TemplateBase.php(101): Smarty_Internal_TemplateBase->display('core/api_group_...')
#6 /data/modules/Core/pages/panel/api.php(468): TemplateBase->displayTemplate('core/api_group_...', Object(Smarty))
#7 /data/index.php(86): require('/data/modules/C...')
#8 {main}
  thrown
```

**Comment by samerton** [comment]
@Derkades with the reinstall would the cache/templates_c directory have been cleared?

**Comment by Derkades** [comment]
Yes, with a reinstall it shut down the webserver and database, removed the website and database directories, started webserver and database, initialized new database, downloaded and extracted new zip

**Comment by samerton** [comment]
@Derkades any luck with https://github.com/NamelessMC/Nameless/commit/8445ea62a93dffbe9f534ba95cf0f5c0f0e00db3 ?

**Comment by Derkades** [comment]
It's fixed
