### ISSUE TITLE
All pages refusing to load due to error

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2065]
Seems to randomly appear and disappear, only for users not logged in. Unfortunately I cannot be more helpful than that, hopefully you can figure it out.
```
[2021-01-22, 10:18:44] /data/core/classes/DB.php(76): Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null in /data/core/classes/DB.php:76
Stack trace:
#0 /data/core/classes/DB.php(76): PDOStatement->execute()
#1 /data/core/classes/DB.php(177): DB->createQuery('INSERT INTO nl2...', Array)
#2 /data/core/classes/Log.php(224): DB->insert('nl2_logs', Array)
#3 /data/core/classes/Util.php(502): Log->log('curl_error', '')
#4 /data/modules/Core/widgets/ServerStatusWidget.php(46): Util::curlGetContents('http://nameless...')
#5 /data/core/classes/Widgets.php(100): ServerStatusWidget->initialise()
#6 /data/modules/Core/pages/home.php(54): Widgets->getWidgets('right')
#7 /data/modules/Core/pages/index.php(16): require('/data/modules/C...')
#8 /data/index.php(72): require('/data/modules/C...')
#9 {main}
```

**Comment by Aberdeener** [comment]
Originating from here
https://github.com/NamelessMC/Nameless/blob/a96e228f7da8e82a13d2d7ccfc45937099b84689/core/classes/Log.php#L218
But not sure why this would fail randomly...

**Comment by Derkades** [comment]
It seems to be permanent now, see https://www.namelessmc.site/

**Comment by Aberdeener** [comment]
Confirmed to fix the site Derk mentioned. Closing unless this occurs again
