### ISSUE TITLE
Cache erase - Key 'update_check' not found

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2066]
It could be an issue with the Forms or Members module but since it happens with both it may be a NamelessMC issue (unless code was copy pasted between them)

```
[2021-01-20, 10:45:19] /data/core/classes/Cache.php(170): Uncaught Exception: Error: erase() - Key 'update_check' not found. in /data/core/classes/Cache.php:170
Stack trace:
#0 /data/modules/Forms/module.php(48): Cache->erase('update_check')
#1 /data/modules/Forms/init.php(17): Forms_Module->__construct(Object(Language), Object(Language), Object(Pages), Object(Queries), Object(Navigation), Object(Cache))
#2 /data/modules/Core/pages/panel/modules.php(44): require_once('/data/modules/F...')
#3 /data/index.php(86): require('/data/modules/C...')
#4 {main}
```
```
[2021-01-20, 10:47:59] /data/core/classes/Cache.php(170): Uncaught Exception: Error: erase() - Key 'update_check' not found. in /data/core/classes/Cache.php:170
Stack trace:
#0 /data/modules/Members/module.php(38): Cache->erase('update_check')
#1 /data/modules/Members/init.php(18): Members_Module->__construct(Object(Language), Object(Pages), Object(Navigation), Object(Cache))
#2 /data/modules/Core/pages/panel/modules.php(44): require_once('/data/modules/M...')
#3 /data/index.php(86): require('/data/modules/C...')
#4 {main}
```

**Comment by samerton** [comment]
These are module errors, not Nameless errors - @partydragen
