### ISSUE TITLE
Error in /data/core/classes/DB.php

### ISSUE THREAD

**Issue by wiruwiru** [NamelessMC/Nameless#2229]
When I want to change the general settings (language and time zone) I get this error but I honestly have no idea how to solve it, I know it is something from mysql but I don't know if you have to touch the .php file or it is fixed from phpmyadmin

```
Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /data/core/classes/DB.php:76
Stack trace:
#0 /data/core/classes/DB.php(76): PDOStatement->execute()
#1 /data/core/classes/DB.php(195): DB->createQuery('UPDATE nl2_lang...', Array)
#2 /data/core/classes/Queries.php(44): DB->update('nl2_languages', NULL, Array)
#3 /data/modules/Core/pages/panel/general_settings.php(105): Queries->update('languages', NULL, Array)
#4 /data/index.php(86): require('/data/modules/C...')
#5 {main}
```

**Comment by wiruwiru** [comment]
Fix it manually modifying the language from phpmyadmin from your nl2_languages ​​table
