### ISSUE TITLE
After Update Internal server error 500 - then Fatal Error

### ISSUE THREAD

**Issue by idepato** [NamelessMC/Nameless#2851]
### Describe the issue

UPDATE: Now my page is not available. - www.klancraft.eu

I have a issue. 

**After i updated Nameless to new version i had a problem. I had a 500 intenral server error. Then i looked on the logs on my hosting and this shows me this:** 

```
Log klancraft.eu, www.klancraft.eu, obchod.klancraft.eu, wl.klancraft.eu, dynmap.klancraft.eu, dev.klancraft.eu, panel.klancraft.eu, klancrafteu
Date: 2022-06-12 21:03:06 - 2022-06-12 21:13:06
Cluster: 6

[Sun Jun 12 21:06:11 2022] [alert] [client 178.40.16.97] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here
[Sun Jun 12 21:06:11 2022] [alert] [client 178.40.16.97] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/
[Sun Jun 12 21:06:37 2022] [alert] [client 147.78.168.66] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here
[Sun Jun 12 21:06:37 2022] [alert] [client 147.78.168.66] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/
[Sun Jun 12 21:06:47 2022] [alert] [client 147.78.168.66] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.google.com/
[Sun Jun 12 21:06:48 2022] [alert] [client 147.78.168.66] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/
[Sun Jun 12 21:06:58 2022] [alert] [client 178.40.16.97] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here
[Sun Jun 12 21:06:58 2022] [alert] [client 178.40.16.97] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/
[Sun Jun 12 21:06:59 2022] [alert] [client 178.40.16.97] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here
[Sun Jun 12 21:06:59 2022] [alert] [client 178.40.16.97] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/
[Sun Jun 12 21:10:31 2022] [alert] [client 109.236.112.167] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here
[Sun Jun 12 21:10:31 2022] [alert] [client 109.236.112.167] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/easy-install.php
[Sun Jun 12 21:10:45 2022] [alert] [client 109.236.112.167] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here
[Sun Jun 12 21:10:45 2022] [alert] [client 109.236.112.167] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/easy-install.php
[Sun Jun 12 21:10:52 2022] [alert] [client 109.236.112.167] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here
[Sun Jun 12 21:10:52 2022] [alert] [client 109.236.112.167] /web/htdocs6/klancrafteu/home/www/.htaccess: Option MultiViews not allowed here, referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'Smarty_Internal_TemplateCompilerBase' not found in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php:17
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #0 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(476): include()
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #1 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(344): Composer\\Autoload\\includeFile('/web/htdocs6/kl...')
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #4 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(647): class_exists('Smarty_Internal...')
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #5 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(183): Smarty_Internal_Template->loadCompiler()
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #6 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php on line 17
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'Smarty_Internal_TemplateCompilerBase' not found in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php:17
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #0 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(476): include()
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #1 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(344): Composer\\Autoload\\includeFile('/web/htdocs6/kl...')
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #4 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(647): class_exists('Smarty_Internal...')
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #5 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(183): Smarty_Internal_Template->loadCompiler()
[Sun Jun 12 21:11:30 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #6 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php on line 17
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'Smarty_Internal_TemplateCompilerBase' not found in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php:17, referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #0 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(476): include(), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #1 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(344): Composer\\Autoload\\includeFile('/web/htdocs6/kl...'), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #4 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(647): class_exists('Smarty_Internal...'), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #5 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(183): Smarty_Internal_Template->loadCompiler(), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #6 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php on line 17, referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'Smarty_Internal_TemplateCompilerBase' not found in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php:17, referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #0 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(476): include(), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #1 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(344): Composer\\Autoload\\includeFile('/web/htdocs6/kl...'), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #4 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(647): class_exists('Smarty_Internal...'), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #5 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(183): Smarty_Internal_Template->loadCompiler(), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #6 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php on line 17, referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: Stack trace:, referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Smarty_Internal...'), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #3 [internal function]: spl_autoload_call('Smarty_Internal...'), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: Stack trace:, referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Smarty_Internal...'), referer: https://www.klancraft.eu/
[Sun Jun 12 21:11:31 2022] [warn] [client 109.236.112.167] mod_fcgid: stderr: #3 [internal function]: spl_autoload_call('Smarty_Internal...'), referer: https://www.klancraft.eu/

# End of file 
```

**After this i delete Open Multiview from .httpacces and then i had this Error on my website.** 
```
Fatal error: Uncaught Error: Class 'Smarty_Internal_TemplateCompilerBase' not found in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php:17 Stack trace: #0 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(476): include() #1 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile('/web/htdocs6/kl...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Smarty_Internal...') #3 [internal function]: spl_autoload_call('Smarty_Internal...') #4 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(647): class_exists('Smarty_Internal...') #5 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(183): Smarty_Internal_Template->loadCompiler() #6 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php on line 17

Fatal error: Uncaught Error: Class 'Smarty_Internal_TemplateCompilerBase' not found in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php:17 Stack trace: #0 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(476): include() #1 /web/htdocs6/klancrafteu/home/www/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile('/web/htdocs6/kl...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Smarty_Internal...') #3 [internal function]: spl_autoload_call('Smarty_Internal...') #4 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(647): class_exists('Smarty_Internal...') #5 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(183): Smarty_Internal_Template->loadCompiler() #6 /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(141): Smarty_Template_Compiled->compileTemplateSource(Object in /web/htdocs6/klancrafteu/home/www/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php on line 17
```

Thanks for the help

### NamelessMC Version

2.0.0-pr13

**Comment by Derkades** [comment]
The class seems to exist for me, so I'd suggest re-uploading the vendor directory in case you missed a few files
