### ISSUE TITLE
Unexpected error: Unknown API error: false

### ISSUE THREAD

**Issue by DexterSK** [NamelessMC/Nameless#3053]
### Describe the issue

[06:53:32 INFO]: [NamelessMC] [Nameless-Java-API Debug] Making connection GET to http://localhost/index.php?route=/api/v2/UACeRy79pldtKxDfLu4N1gS3oZrwqFiX/info
[06:53:33 INFO]: [Nameless-Store] Fetched pending players (0 found).
[06:53:33 INFO]: [NamelessMC] [Nameless-Java-API Debug] Website response body, after 152ms:
{
    "nameless_version": "2.0.0-pr12",
    "language": "Czech",
    "version_update": {
        "update": true,
        "version": "unknown",
        "urgent": false
    },
    "modules": [
        "Core",
        "Forum",
        "Store",
        "CustomDropdown",
        "Friends",
        "Staff",
        "Vote",
        "Rules"
    ],
    "error": false
}
[06:53:33 ERROR]: [NamelessMC] Unexpected error: Unknown API error: false
[06:53:33 ERROR]: [NamelessMC] com.namelessmc.plugin.lib.nameless-api.exception.NamelessException: Unknown API error: false
        at Nameless-Plugin-Spigot-3.2.0.jar//com.namelessmc.plugin.lib.nameless-api.RequestHandler.makeConnection(RequestHandler.java:218)
        at Nameless-Plugin-Spigot-3.2.0.jar//com.namelessmc.plugin.lib.nameless-api.RequestHandler.get(RequestHandler.java:87)
        at Nameless-Plugin-Spigot-3.2.0.jar//com.namelessmc.plugin.lib.nameless-api.NamelessAPI.website(NamelessAPI.java:101)
        at Nameless-Plugin-Spigot-3.2.0.jar//com.namelessmc.plugin.common.ApiProvider.api(ApiProvider.java:120)
        at Nameless-Plugin-Spigot-3.2.0.jar//com.namelessmc.plugin.common.UserCache.lambda$update$0(UserCache.java:45)
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

### NamelessMC Version

2.0.0

**Comment by Derkades** [comment]
The plugin supports pr13 and up, you are still using pr12.

**Comment by DexterSK** [comment]
ah thanks
