### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by trentrbtaylor** [NamelessMC/Nameless#87]
Every time I try and install NamelessMC, I get this error.

[02-Feb-2016 00:20:52 Europe/London] PHP Notice:  Undefined index: config in /home/trentrtaylor/public_html/mc/core/classes/Config.php on line 5
[02-Feb-2016 00:20:55 Europe/London] PHP Notice:  Undefined index: config in /home/trentrtaylor/public_html/mc/core/classes/Config.php on line 5
[02-Feb-2016 00:20:57 Europe/London] PHP Notice:  Undefined index: config in /home/trentrtaylor/public_html/mc/core/classes/Config.php on line 5
[02-Feb-2016 00:21:23 Europe/London] PHP Notice:  Undefined index: config in /home/trentrtaylor/public_html/mc/core/classes/Config.php on line 5
[02-Feb-2016 00:21:23 Europe/London] PHP Notice:  Undefined index: config in /home/trentrtaylor/public_html/mc/core/classes/Config.php on line 5
[02-Feb-2016 00:21:24 Europe/London] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'TripexDatabase.nl1_users_session' doesn't exist' in /home/trentrtaylor/public_html/mc/core/classes/DB.php:42
Stack trace:
#0 /home/trentrtaylor/public_html/mc/core/classes/DB.php(42): PDOStatement->execute()
#1 /home/trentrtaylor/public_html/mc/core/classes/DB.php(104): DB->query('SELECT * FROM n...', Array)
#2 /home/trentrtaylor/public_html/mc/core/classes/DB.php(134): DB->action('SELECT *', 'users_session', Array)
#3 /home/trentrtaylor/public_html/mc/core/init.php(76): DB->get('users_session', Array)
#4 /home/trentrtaylor/public_html/mc/index.php(32): require('/home/trentrtay...')
#5 {main}
  thrown in /home/trentrtaylor/public_html/mc/core/classes/DB.php on line 42
[02-Feb-2016 00:21:49 Europe/London] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'TripexDatabase.nl1_users_session' doesn't exist' in /home/trentrtaylor/public_html/mc/core/classes/DB.php:42
Stack trace:
#0 /home/trentrtaylor/public_html/mc/core/classes/DB.php(42): PDOStatement->execute()
#1 /home/trentrtaylor/public_html/mc/core/classes/DB.php(104): DB->query('SELECT * FROM n...', Array)
#2 /home/trentrtaylor/public_html/mc/core/classes/DB.php(134): DB->action('SELECT *', 'users_session', Array)
#3 /home/trentrtaylor/public_html/mc/core/init.php(76): DB->get('users_session', Array)
#4 /home/trentrtaylor/public_html/mc/index.php(32): require('/home/trentrtay...')
#5 {main}
  thrown in /home/trentrtaylor/public_html/mc/core/classes/DB.php on line 42

**Comment by samerton** [comment]
It looks like NamelessMC isn't installed in the root directory of your webserver (it is in the /mc directory); this is a requirement.

**Comment by trentrbtaylor** [comment]
When I use it in the root directory, I always get a 404 error after clicking new install..

**Comment by samerton** [comment]
Check to see if there is a file in the root directory named ".htaccess" containing [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/.htaccess).

If there is, try following [this guide](http://askubuntu.com/questions/48362/how-to-enable-mod-rewrite-in-apache/48363#48363) (for Ubuntu).

**Comment by trentrbtaylor** [comment]
With Godaddy, you cannot see the .htaccess file, although you can make a new one and overwrite it. I'll do that.

**Comment by samerton** [comment]
I'm going to close this issue as I believe it's a configuration issue on the host's side.
